openapi: 3.0.0
info:
  contact:
    email: contact@yousign.com
    name: Support
    url: https://yousign.com/contact
  description: Build the best experience of digital signature through your own platform. Increase your conversion rates, leverage your data and reduce your costs with Yousign API.
  license:
    name: proprietary
    url: https://yousign.com/terms
  title: Public Api v3 Applicant Watchlist Verification API
  version: '3.0'
servers:
- description: Sandbox URL
  url: https://api-sandbox.yousign.app/v3
- description: Production URL
  url: https://api.yousign.app/v3
security:
- bearerAuth: []
tags:
- description: Check if individuals appear on international sanctions lists or as politically exposed persons (PEPs).
  name: Watchlist Verification
paths:
  /verifications/watchlists:
    get:
      description: 'Returns the list of all Watchlist Verifications within your organization.

        You can limit the number of items returned by using filters and pagination.

        Consult our [guide](https://developers.yousign.com/docs/watchlists-verification) for more details and examples.

        '
      operationId: get-verifications-watchlists
      parameters:
      - description: After cursor (pagination)
        in: query
        name: after
        required: false
        schema:
          minLength: 1
          type: string
      - description: The limit of items count to retrieve.
        in: query
        name: limit
        required: false
        schema:
          default: 100
          maximum: 100
          minimum: 1
          type: integer
      - description: 'Filter by `status`. Allowed operators: `eq`.

          Example: `status[eq]=verified`

          '
        example:
          eq:
          - verified
        explode: true
        in: query
        name: status
        required: false
        schema:
          description: Filter by status.
          minProperties: 1
          type: object
        style: deepObject
      - description: 'Filter by `workspace_id`. Allowed operators: `eq`.

          Example: `workspace_id[eq]=9b6ed2f3-244f-487a-baa1-bbe4f51c8748`

          '
        example:
          eq:
          - 9b6ed2f3-244f-487a-baa1-bbe4f51c8748
        explode: true
        in: query
        name: workspace_id
        required: false
        schema:
          description: Filter by workspace_id.
          minProperties: 1
          type: object
        style: deepObject
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/get_verifications_watchlists_200_response'
          description: OK
          headers:
            RateLimit-Limit:
              $ref: '#/components/headers/rateLimit-limit'
            X-RateLimit-Limit-Hour:
              $ref: '#/components/headers/rateLimit-limit-hour'
            X-RateLimit-Limit-Minute:
              $ref: '#/components/headers/rateLimit-limit-minute'
            RateLimit-Remaining:
              $ref: '#/components/headers/rateLimit-remaining'
            X-RateLimit-Remaining-Hour:
              $ref: '#/components/headers/rateLimit-remaining-hour'
            X-RateLimit-Remaining-Minute:
              $ref: '#/components/headers/rateLimit-remaining-minute'
            RateLimit-Reset:
              $ref: '#/components/headers/rateLimit-reset'
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequestResponse'
          description: Bad request
          headers:
            RateLimit-Limit:
              $ref: '#/components/headers/rateLimit-limit'
            X-RateLimit-Limit-Hour:
              $ref: '#/components/headers/rateLimit-limit-hour'
            X-RateLimit-Limit-Minute:
              $ref: '#/components/headers/rateLimit-limit-minute'
            RateLimit-Remaining:
              $ref: '#/components/headers/rateLimit-remaining'
            X-RateLimit-Remaining-Hour:
              $ref: '#/components/headers/rateLimit-remaining-hour'
            X-RateLimit-Remaining-Minute:
              $ref: '#/components/headers/rateLimit-remaining-minute'
            RateLimit-Reset:
              $ref: '#/components/headers/rateLimit-reset'
        '401':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UnauthorizedResponse'
          description: Access unauthorized
          headers:
            RateLimit-Limit:
              $ref: '#/components/headers/rateLimit-limit'
            X-RateLimit-Limit-Hour:
              $ref: '#/components/headers/rateLimit-limit-hour'
            X-RateLimit-Limit-Minute:
              $ref: '#/components/headers/rateLimit-limit-minute'
            RateLimit-Remaining:
              $ref: '#/components/headers/rateLimit-remaining'
            X-RateLimit-Remaining-Hour:
              $ref: '#/components/headers/rateLimit-remaining-hour'
            X-RateLimit-Remaining-Minute:
              $ref: '#/components/headers/rateLimit-remaining-minute'
            RateLimit-Reset:
              $ref: '#/components/headers/rateLimit-reset'
        '403':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ForbiddenResponse'
          description: Access forbidden
          headers:
            RateLimit-Limit:
              $ref: '#/components/headers/rateLimit-limit'
            X-RateLimit-Limit-Hour:
              $ref: '#/components/headers/rateLimit-limit-hour'
            X-RateLimit-Limit-Minute:
              $ref: '#/components/headers/rateLimit-limit-minute'
            RateLimit-Remaining:
              $ref: '#/components/headers/rateLimit-remaining'
            X-RateLimit-Remaining-Hour:
              $ref: '#/components/headers/rateLimit-remaining-hour'
            X-RateLimit-Remaining-Minute:
              $ref: '#/components/headers/rateLimit-remaining-minute'
            RateLimit-Reset:
              $ref: '#/components/headers/rateLimit-reset'
        '405':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MethodNotAllowed'
          description: This method is not allowed
          headers:
            RateLimit-Limit:
              $ref: '#/components/headers/rateLimit-limit'
            X-RateLimit-Limit-Hour:
              $ref: '#/components/headers/rateLimit-limit-hour'
            X-RateLimit-Limit-Minute:
              $ref: '#/components/headers/rateLimit-limit-minute'
            RateLimit-Remaining:
              $ref: '#/components/headers/rateLimit-remaining'
            X-RateLimit-Remaining-Hour:
              $ref: '#/components/headers/rateLimit-remaining-hour'
            X-RateLimit-Remaining-Minute:
              $ref: '#/components/headers/rateLimit-remaining-minute'
            RateLimit-Reset:
              $ref: '#/components/headers/rateLimit-reset'
            Retry-After:
              $ref: '#/components/headers/retry-after'
        '429':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TooManyRequestsResponse'
          description: Too Many Requests, please try again later.
          headers:
            RateLimit-Limit:
              $ref: '#/components/headers/rateLimit-limit'
            X-RateLimit-Limit-Hour:
              $ref: '#/components/headers/rateLimit-limit-hour'
            X-RateLimit-Limit-Minute:
              $ref: '#/components/headers/rateLimit-limit-minute'
            RateLimit-Remaining:
              $ref: '#/components/headers/rateLimit-remaining'
            X-RateLimit-Remaining-Hour:
              $ref: '#/components/headers/rateLimit-remaining-hour'
            X-RateLimit-Remaining-Minute:
              $ref: '#/components/headers/rateLimit-remaining-minute'
            RateLimit-Reset:
              $ref: '#/components/headers/rateLimit-reset'
            Retry-After:
              $ref: '#/components/headers/retry-after'
        '500':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerError'
          description: Internal Server Error
          headers:
            RateLimit-Limit:
              $ref: '#/components/headers/rateLimit-limit'
            X-RateLimit-Limit-Hour:
              $ref: '#/components/headers/rateLimit-limit-hour'
            X-RateLimit-Limit-Minute:
              $ref: '#/components/headers/rateLimit-limit-minute'
            RateLimit-Remaining:
              $ref: '#/components/headers/rateLimit-remaining'
            X-RateLimit-Remaining-Hour:
              $ref: '#/components/headers/rateLimit-remaining-hour'
            X-RateLimit-Remaining-Minute:
              $ref: '#/components/headers/rateLimit-remaining-minute'
            RateLimit-Reset:
              $ref: '#/components/headers/rateLimit-reset'
      summary: List Watchlist Verifications
      tags:
      - Watchlist Verification
    post:
      description: 'Initiate a verification to check if a person appears on international sanctions lists or as a politically exposed person (PEP).

        '
      operationId: post-verifications-watchlists
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InitiateWatchlist'
      responses:
        '201':
          content:
            application/json:
              examples:
                pending:
                  summary: 'Pending - Verification Is In Progress: On Creation The Status Is Always Pending'
                  value:
                    id: 9a93d3b5-fb3b-4abf-9e70-26315b33506c
                    workspace_id: 9a93d3b5-fb3b-4abf-9e70-26315b33506c
                    workflow_session_id: 0ef334d2-7f36-4643-8a2a-4283b4a3e4a4
                    previous_attempt_id: 9412b83b-b4b9-4a94-97b5-2b43dfa4cde4
                    created_at: '2025-02-12T23:59:59+00:00'
                    updated_at: '2025-02-12T23:59:59+00:00'
                    status: pending
                    data_anonymized: false
                    data:
                      politically_exposed_person:
                        active: false
                        positions: []
                      sanctions:
                        active: false
                        records: []
              schema:
                $ref: '#/components/schemas/WatchlistFull'
          description: Created
          headers:
            RateLimit-Limit:
              $ref: '#/components/headers/rateLimit-limit'
            X-RateLimit-Limit-Hour:
              $ref: '#/components/headers/rateLimit-limit-hour'
            X-RateLimit-Limit-Minute:
              $ref: '#/components/headers/rateLimit-limit-minute'
            RateLimit-Remaining:
              $ref: '#/components/headers/rateLimit-remaining'
            X-RateLimit-Remaining-Hour:
              $ref: '#/components/headers/rateLimit-remaining-hour'
            X-RateLimit-Remaining-Minute:
              $ref: '#/components/headers/rateLimit-remaining-minute'
            RateLimit-Reset:
              $ref: '#/components/headers/rateLimit-reset'
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequestResponse'
          description: Bad request
          headers:
            RateLimit-Limit:
              $ref: '#/components/headers/rateLimit-limit'
            X-RateLimit-Limit-Hour:
              $ref: '#/components/headers/rateLimit-limit-hour'
            X-RateLimit-Limit-Minute:
              $ref: '#/components/headers/rateLimit-limit-minute'
            RateLimit-Remaining:
              $ref: '#/components/headers/rateLimit-remaining'
            X-RateLimit-Remaining-Hour:
              $ref: '#/components/headers/rateLimit-remaining-hour'
            X-RateLimit-Remaining-Minute:
              $ref: '#/components/headers/rateLimit-remaining-minute'
            RateLimit-Reset:
              $ref: '#/components/headers/rateLimit-reset'
        '401':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UnauthorizedResponse'
          description: Access unauthorized
          headers:
            RateLimit-Limit:
              $ref: '#/components/headers/rateLimit-limit'
            X-RateLimit-Limit-Hour:
              $ref: '#/components/headers/rateLimit-limit-hour'
            X-RateLimit-Limit-Minute:
              $ref: '#/components/headers/rateLimit-limit-minute'
            RateLimit-Remaining:
              $ref: '#/components/headers/rateLimit-remaining'
            X-RateLimit-Remaining-Hour:
              $ref: '#/components/headers/rateLimit-remaining-hour'
            X-RateLimit-Remaining-Minute:
              $ref: '#/components/headers/rateLimit-remaining-minute'
            RateLimit-Reset:
              $ref: '#/components/headers/rateLimit-reset'
        '403':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ForbiddenResponse'
          description: Access forbidden
          headers:
            RateLimit-Limit:
              $ref: '#/components/headers/rateLimit-limit'
            X-RateLimit-Limit-Hour:
              $ref: '#/components/headers/rateLimit-limit-hour'
            X-RateLimit-Limit-Minute:
              $ref: '#/components/headers/rateLimit-limit-minute'
            RateLimit-Remaining:
              $ref: '#/components/headers/rateLimit-remaining'
            X-RateLimit-Remaining-Hour:
              $ref: '#/components/headers/rateLimit-remaining-hour'
            X-RateLimit-Remaining-Minute:
              $ref: '#/components/headers/rateLimit-remaining-minute'
            RateLimit-Reset:
              $ref: '#/components/headers/rateLimit-reset'
        '405':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MethodNotAllowed'
          description: This method is not allowed
          headers:
            RateLimit-Limit:
              $ref: '#/components/headers/rateLimit-limit'
            X-RateLimit-Limit-Hour:
              $ref: '#/components/headers/rateLimit-limit-hour'
            X-RateLimit-Limit-Minute:
              $ref: '#/components/headers/rateLimit-limit-minute'
            RateLimit-Remaining:
              $ref: '#/components/headers/rateLimit-remaining'
            X-RateLimit-Remaining-Hour:
              $ref: '#/components/headers/rateLimit-remaining-hour'
            X-RateLimit-Remaining-Minute:
              $ref: '#/components/headers/rateLimit-remaining-minute'
            RateLimit-Reset:
              $ref: '#/components/headers/rateLimit-reset'
            Retry-After:
              $ref: '#/components/headers/retry-after'
        '415':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UnsupportedMediaTypeResponse'
          description: UnsupportedMediaType
          headers:
            RateLimit-Limit:
              $ref: '#/components/headers/rateLimit-limit'
            X-RateLimit-Limit-Hour:
              $ref: '#/components/headers/rateLimit-limit-hour'
            X-RateLimit-Limit-Minute:
              $ref: '#/components/headers/rateLimit-limit-minute'
            RateLimit-Remaining:
              $ref: '#/components/headers/rateLimit-remaining'
            X-RateLimit-Remaining-Hour:
              $ref: '#/components/headers/rateLimit-remaining-hour'
            X-RateLimit-Remaining-Minute:
              $ref: '#/components/headers/rateLimit-remaining-minute'
            RateLimit-Reset:
              $ref: '#/components/headers/rateLimit-reset'
        '429':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TooManyRequestsResponse'
          description: Too Many Requests, please try again later.
          headers:
            RateLimit-Limit:
              $ref: '#/components/headers/rateLimit-limit'
            X-RateLimit-Limit-Hour:
              $ref: '#/components/headers/rateLimit-limit-hour'
            X-RateLimit-Limit-Minute:
              $ref: '#/components/headers/rateLimit-limit-minute'
            RateLimit-Remaining:
              $ref: '#/components/headers/rateLimit-remaining'
            X-RateLimit-Remaining-Hour:
              $ref: '#/components/headers/rateLimit-remaining-hour'
            X-RateLimit-Remaining-Minute:
              $ref: '#/components/headers/rateLimit-remaining-minute'
            RateLimit-Reset:
              $ref: '#/components/headers/rateLimit-reset'
            Retry-After:
              $ref: '#/components/headers/retry-after'
        '500':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerError'
          description: Internal Server Error
          headers:
            RateLimit-Limit:
              $ref: '#/components/headers/rateLimit-limit'
            X-RateLimit-Limit-Hour:
              $ref: '#/components/headers/rateLimit-limit-hour'
            X-RateLimit-Limit-Minute:
              $ref: '#/components/headers/rateLimit-limit-minute'
            RateLimit-Remaining:
              $ref: '#/components/headers/rateLimit-remaining'
            X-RateLimit-Remaining-Hour:
              $ref: '#/components/headers/rateLimit-remaining-hour'
            X-RateLimit-Remaining-Minute:
              $ref: '#/components/headers/rateLimit-remaining-minute'
            RateLimit-Reset:
              $ref: '#/components/headers/rateLimit-reset'
      summary: Initiate a new Watchlist Verification
      tags:
      - Watchlist Verification
  /verifications/watchlists/{watchlistVerificationId}:
    get:
      description: 'Retrieve a specific Watchlist Verification by its ID.

        Returns details about sanctions and politically exposed person status.

        '
      operationId: get-verifications-watchlists-id
      parameters:
      - description: Watchlist Verification Id
        in: path
        name: watchlistVerificationId
        required: true
        schema:
          $ref: '#/components/schemas/UUID'
      responses:
        '200':
          content:
            application/json:
              examples:
                verified:
                  summary: Verified result - no data was found
                  value:
                    id: 9a93d3b5-fb3b-4abf-9e70-26315b33506c
                    workspace_id: 9a93d3b5-fb3b-4abf-9e70-26315b33506c
                    created_at: '2025-02-12T23:59:59+00:00'
                    updated_at: '2025-02-13T00:00:00+00:00'
                    status: verified
                    data_anonymized: false
                    workflow_session_id: null
                    previous_attempt_id: null
                    data:
                      politically_exposed_person:
                        active: false
                        positions: []
                      sanctions:
                        active: false
                        records: []
                failed:
                  summary: Failed result - at least 1 PEP or sanction found
                  value:
                    id: 9a93d3b5-fb3b-4abf-9e70-26315b33506c
                    workspace_id: 9a93d3b5-fb3b-4abf-9e70-26315b33506c
                    created_at: '2025-02-12T23:59:59+00:00'
                    updated_at: '2025-02-13T00:00:00+00:00'
                    status: failed
                    data_anonymized: false
                    workflow_session_id: null
                    previous_attempt_id: null
                    data:
                      politically_exposed_person:
                        active: true
                        positions:
                        - title: Minister of Finance
                          active: true
                          country_code: FR
                          started_on: '2022-05-20'
                          ended_on: null
                          sources:
                          - name: Wikidata Politically Exposed Persons
                            url: https://www.opensanctions.org/datasets/wd_peps
                      sanctions:
                        active: true
                        records:
                        - description: Economic sanctions related to illegal actions
                          authority: European Union
                          country_code: EU
                          active: true
                          started_on: '2023-09-15'
                          ended_on: null
                          sources:
                          - name: EU Consolidated Sanctions List
                            url: https://www.opensanctions.org/datasets/eu_fsf
              schema:
                $ref: '#/components/schemas/WatchlistFull'
          description: OK
          headers:
            RateLimit-Limit:
              $ref: '#/components/headers/rateLimit-limit'
            X-RateLimit-Limit-Hour:
              $ref: '#/components/headers/rateLimit-limit-hour'
            X-RateLimit-Limit-Minute:
              $ref: '#/components/headers/rateLimit-limit-minute'
            RateLimit-Remaining:
              $ref: '#/components/headers/rateLimit-remaining'
            X-RateLimit-Remaining-Hour:
              $ref: '#/components/headers/rateLimit-remaining-hour'
            X-RateLimit-Remaining-Minute:
              $ref: '#/components/headers/rateLimit-remaining-minute'
            RateLimit-Reset:
              $ref: '#/components/headers/rateLimit-reset'
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequestResponse'
          description: Bad request
          headers:
            RateLimit-Limit:
              $ref: '#/components/headers/rateLimit-limit'
            X-RateLimit-Limit-Hour:
              $ref: '#/components/headers/rateLimit-limit-hour'
            X-RateLimit-Limit-Minute:
              $ref: '#/components/headers/rateLimit-limit-minute'
            RateLimit-Remaining:
              $ref: '#/components/headers/rateLimit-remaining'
            X-RateLimit-Remaining-Hour:
              $ref: '#/components/headers/rateLimit-remaining-hour'
            X-RateLimit-Remaining-Minute:
              $ref: '#/components/headers/rateLimit-remaining-minute'
            RateLimit-Reset:
              $ref: '#/components/headers/rateLimit-reset'
        '401':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UnauthorizedResponse'
          description: Access unauthorized
          headers:
            RateLimit-Limit:
              $ref: '#/components/headers/rateLimit-limit'
            X-RateLimit-Limit-Hour:
              $ref: '#/components/headers/rateLimit-limit-hour'
            X-RateLimit-Limit-Minute:
              $ref: '#/components/headers/rateLimit-limit-minute'
            RateLimit-Remaining:
              $ref: '#/components/headers/rateLimit-remaining'
            X-RateLimit-Remaining-Hour:
              $ref: '#/components/headers/rateLimit-remaining-hour'
            X-RateLimit-Remaining-Minute:
              $ref: '#/components/headers/rateLimit-remaining-minute'
            RateLimit-Reset:
              $ref: '#/components/headers/rateLimit-reset'
        '403':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ForbiddenResponse'
          description: Access forbidden
          headers:
            RateLimit-Limit:
              $ref: '#/components/headers/rateLimit-limit'
            X-RateLimit-Limit-Hour:
              $ref: '#/components/headers/rateLimit-limit-hour'
            X-RateLimit-Limit-Minute:
              $ref: '#/components/headers/rateLimit-limit-minute'
            RateLimit-Remaining:
              $ref: '#/components/headers/rateLimit-remaining'
            X-RateLimit-Remaining-Hour:
              $ref: '#/components/headers/rateLimit-remaining-hour'
            X-RateLimit-Remaining-Minute:
              $ref: '#/components/headers/rateLimit-remaining-minute'
            RateLimit-Reset:
              $ref: '#/components/headers/rateLimit-reset'
        '404':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFoundResponse'
          description: Resource not found
          headers:
            RateLimit-Limit:
              $ref: '#/components/headers/rateLimit-limit'
            X-RateLimit-Limit-Hour:
              $ref: '#/components/headers/rateLimit-limit-hour'
            X-RateLimit-Limit-Minute:
              $ref: '#/components/headers/rateLimit-limit-minute'
            RateLimit-Remaining:
              $ref: '#/components/headers/rateLimit-remaining'
            X-RateLimit-Remaining-Hour:
              $ref: '#/components/headers/rateLimit-remaining-hour'
            X-RateLimit-Remaining-Minute:
              $ref: '#/components/headers/rateLimit-remaining-minute'
            RateLimit-Reset:
              $ref: '#/components/headers/rateLimit-reset'
        '405':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MethodNotAllowed'
          description: This method is not allowed
          headers:
            RateLimit-Limit:
              $ref: '#/components/headers/rateLimit-limit'
            X-RateLimit-Limit-Hour:
              $ref: '#/components/headers/rateLimit-limit-hour'
            X-RateLimit-Limit-Minute:
              $ref: '#/components/headers/rateLimit-limit-minute'
            RateLimit-Remaining:
              $ref: '#/components/headers/rateLimit-remaining'
            X-RateLimit-Remaining-Hour:
              $ref: '#/components/headers/rateLimit-remaining-hour'
            X-RateLimit-Remaining-Minute:
              $ref: '#/components/headers/rateLimit-remaining-minute'
            RateLimit-Reset:
              $ref: '#/components/headers/rateLimit-reset'
            Retry-After:
              $ref: '#/components/headers/retry-after'
        '429':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TooManyRequestsResponse'
          description: Too Many Requests, please try again later.
          headers:
            RateLimit-Limit:
              $ref: '#/components/headers/rateLimit-limit'
            X-RateLimit-Limit-Hour:
              $ref: '#/components/headers/rateLimit-limit-hour'
            X-RateLimit-Limit-Minute:
              $ref: '#/components/headers/rateLimit-limit-minute'
            RateLimit-Remaining:
              $ref: '#/components/headers/rateLimit-remaining'
            X-RateLimit-Remaining-Hour:
              $ref: '#/components/headers/rateLimit-remaining-hour'
            X-RateLimit-Remaining-Minute:
              $ref: '#/components/headers/rateLimit-remaining-minute'
            RateLimit-Reset:
              $ref: '#/components/headers/rateLimit-reset'
            Retry-After:
              $ref: '#/components/headers/retry-after'
        '500':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerError'
          description: Internal Server Error
          headers:
            RateLimit-Limit:
              $ref: '#/components/headers/rateLimit-limit'
            X-RateLimit-Limit-Hour:
              $ref: '#/components/headers/rateLimit-limit-hour'
            X-RateLimit-Limit-Minute:
              $ref: '#/components/headers/rateLimit-limit-minute'
            RateLimit-Remaining:
              $ref: '#/components/headers/rateLimit-remaining'
            X-RateLimit-Remaining-Hour:
              $ref: '#/components/headers/rateLimit-remaining-hour'
            X-RateLimit-Remaining-Minute:
              $ref: '#/components/headers/rateLimit-remaining-minute'
            RateLimit-Reset:
              $ref: '#/components/headers/rateLimit-reset'
      summary: Retrieve a Watchlist Verification
      tags:
      - Watchlist Verification
components:
  headers:
    rateLimit-remaining:
      description: The number of requests remaining in the current rate limit window
      schema:
        type: integer
    rateLimit-reset:
      description: The remaining time until the rate limit resets in seconds
      schema:
        type: integer
    rateLimit-remaining-hour:
      description: The number of requests remaining in the current hour rate limit window
      schema:
        type: integer
    rateLimit-limit:
      description: The maximum number of requests that the consumer is permitted to make in a given period
      schema:
        type: integer
    retry-after:
      description: Retry the request after X seconds
      schema:
        type: integer
    rateLimit-remaining-minute:
      description: The number of requests remaining in the current minute rate limit window
      schema:
        type: integer
    rateLimit-limit-minute:
      description: The maximum number of requests that the consumer is permitted to make in an minute window
      schema:
        type: integer
    rateLimit-limit-hour:
      description: The maximum number of requests that the consumer is permitted to make in an hour window
      schema:
        type: integer
  schemas:
    InternalServerError:
      properties:
        type:
          example: about:blank
          type: string
        detail:
          example: Something wrong occurred.
          type: string
      required:
      - detail
      - type
      title: InternalServerError
      type: object
    WatchlistFull_allOf_data:
      description: Verification result data
      properties:
        politically_exposed_person:
          $ref: '#/components/schemas/WatchlistFull_allOf_data_politically_exposed_person'
        sanctions:
          $ref: '#/components/schemas/WatchlistFull_allOf_data_sanctions'
      required:
      - politically_exposed_person
      - sanctions
      type: object
    TooManyRequestsResponse:
      properties:
        message:
          type: string
      required:
      - message
      title: TooManyRequestsResponse
      type: object
    WatchlistFull_allOf_data_politically_exposed_person_sources:
      properties:
        name:
          description: Name of the source
          example: Wikidata Politically Exposed Persons
          nullable: true
          type: string
        url:
          description: URL of the source
          example: https://www.opensanctions.org/datasets/wd_peps
          nullable: true
          type: string
      required:
      - name
      - url
      type: object
    WatchlistMeta:
      properties:
        id:
          $ref: '#/components/schemas/UUID'
        workspace_id:
          description: The Workspace ID in which the verification has been created.
          example: 9a93d3b5-fb3b-4abf-9e70-26315b33506c
          format: uuid
          type: string
        created_at:
          description: Creation date of the Watchlist Verification.
          example: '2025-02-12T23:59:59Z'
          format: date-time
          type: string
        updated_at:
          description: Update date of the Watchlist Verification.
          example: '2025-02-12T23:59:59Z'
          format: date-time
          type: string
        status:
          $ref: '#/components/schemas/WatchlistStatus'
        data_anonymized:
          description: 'Indicates if the data related to the Watchlist Verification has been anonymized.

            If set to `true`, the data are removed and most fields will be NULL.

            '
          example: false
          type: boolean
        workflow_session_id:
          $ref: '#/components/schemas/WorkflowSessionId'
        previous_attempt_id:
          $ref: '#/components/schemas/PreviousAttemptId'
      required:
      - created_at
      - data_anonymized
      - id
      - previous_attempt_id
      - status
      - updated_at
      - workflow_session_id
      - workspace_id
      title: WatchlistMeta
      type: object
    WatchlistFull_allOf_data_politically_exposed_person:
      description: Information about politically exposed person status
      properties:
        active:
          description: Whether the person is currently politically exposed
          type: boolean
        positions:
          items:
            $ref: '#/components/schemas/WatchlistFull_allOf_data_politically_exposed_person_positions'
          type: array
      required:
      - active
      - positions
      type: object
    UnsupportedMediaTypeResponse:
      properties:
        type:
          type: string
        detail:
          type: string
      required:
      - detail
      - type
      title: UnsupportedMediaTypeResponse
      type: object
    WatchlistFull_allOf_data_sanctions:
      description: List of sanctions against the person
      properties:
        active:
          description: Whether the person is currently sanctioned.
          type: boolean
        records:
          items:
            $ref: '#/components/schemas/WatchlistFull_allOf_data_sanctions_records'
          type: array
      required:
      - active
      - records
      type: object
    MethodNotAllowed:
      properties:
        message:
          type: string
      required:
      - message
      title: MethodNotAllowed
      type: object
    InitiateWatchlist_natural_person:
      description: Information about the person to check
      properties:
        first_name:
          description: First name of the person
          example: Emmanuel
          nullable: false
          type: string
        last_name:
          description: Last name of the person
          example: Macron
          nullable: false
          type: string
        born_on:
          description: Date of birth of the person (YYYY-MM-DD)
          example: '1977-12-21'
          format: date
          nullable: false
          type: string
      required:
      - born_on
      - first_name
      - last_name
      type: object
    NotFoundResponse:
      properties:
        type:
          type: string
        detail:
          type: string
      required:
      - detail
      - type
      title: NotFoundResponse
      type: object
    WatchlistFull_allOf_data_sanctions_records:
      properties:
        description:
          description: Description of the sanction
          example: Management ban
          nullable: true
          type: string
        authority:
          description: Authority that issued the sanction
          example: Commercial Court of Paris
          nullable: true
          type: string
        country_code:
          description: ISO country code where the sanction is applicable
          example: FR
          format: ISO 3166-1 alpha-2
          nullable: true
          type: string
        active:
          description: Whether the sanction is currently active
          example: false
          type: boolean
        started_on:
          description: Date when the sanction started
          example: '2020-01-01'
          nullable: true
          type: string
        ended_on:
          description: Date when the sanction ended − null if ongoing
          example: '2021-01-01'
          nullable: true
          type: string
        sources:
          description: Sources of this information
          items:
            $ref: '#/components/schemas/WatchlistFull_allOf_data_sanctions_sources'
          type: array
      required:
      - active
      - authority
      - country_code
      - description
      - ended_on
      - sources
      - started_on
      type: object
    BadRequestResponse:
      properties:
        type:
          type: string
        detail:
          type: string
      required:
      - detail
      - type
      title: BadRequestResponse
      type: object
    ForbiddenResponse:
      properties:
        type:
          type: string
        detail:
          type: string
      required:
      - detail
      - type
      title: ForbiddenResponse
      type: object
    UnauthorizedResponse:
      properties:
        type:
          type: string
        detail:
          type: string
      required:
      - detail
      - type
      title: UnauthorizedResponse
      type: object
    WatchlistFull:
      allOf:
      - $ref: '#/components/schemas/WatchlistMeta'
      - properties:
          data:
            $ref: '#/components/schemas/WatchlistFull_allOf_data'
        required:
        - data
        type: object
      title: WatchlistFull
      type: object
    UUID:
      description: The unique identifier for a resource.
      example: 9a93d3b5-fb3b-4abf-9e70-26315b33506c
      format: uuid
      type: string
    WatchlistStatus:
      description: Status of the Watchlist Verification.
      enum:
      - pending
      - verified
      - failed
      - inconclusive
      example: verified
      type: string
    WatchlistFull_allOf_data_politically_exposed_person_positions:
      properties:
        title:
          description: Title of the political position
          example: Minister of Finance
          nullable: true
          type: string
        active:
          description: Whether the person is currently politically exposed
          example: false
          type: boolean
        country_code:
          description: ISO country code where the position is held
          example: FR
          format: ISO 3166-1 alpha-2
          nullable: true
          type: string
        started_on:
          description: Date when the position started
          example: '2020-01-01'
          nullable: true
          type: string
        ended_on:
          description: Date when the position ended − null if ongoing
          example: '2021-01-01'
          nullable: true
          type: string
        sources:
          description: Sources of this information
          items:
            $ref: '#/components/schemas/WatchlistFull_allOf_data_politically_exposed_person_sources'
          type: array
      required:
      - active
      - country_code
      - ended_on
      - sources
      - started_on
      - title
      type: object
    PreviousAttemptId:
      description: 'ID of the previous attempt within the same `workflow_session_id`.

        Allows continuity between multiple attempts of the same Action.

        Null if this is the first attempt.

        '
      example: 9412b83b-b4b9-4a94-97b5-2b43dfa4cde4
      format: uuid
      nullable: true
      title: Previous Attempt identifier
      type: string
    InitiateWatchlist:
      additionalProperties: false
      properties:
        workspace_id:
          description: 'Scopes the verification to a specific workspace.

            Defaults to the default workspace if not specified.

            '
          example: 9412b83b-b4b9-4a94-97b5-2b43dfa4cde3
          format: uuid
          nullable: true
          type: string
        natural_person:
          $ref: '#/components/schemas/InitiateWatchlist_natural_person'
        workflow_session_id:
          $ref: '#/components/schemas/WorkflowSessionId'
        previous_attempt_id:
          $ref: '#/components/schemas/PreviousAttemptId'
      required:
      - natural_person
      title: Initiate Watchlist Verification
      type: object
    WorkflowSessionId:
      description: 'Unique identifier of a Workflow Session. When provided, an Action is created in the Workflow Session, and this resource is associated with that Action.

        '
      example: 0ef334d2-7f36-4643-8a2a-4283b4a3e4a4
      format: uuid
      nullable: true
      title: Workflow Session identifier
      type: string
    Pagination:
      description: Metadata about the response.
      properties:
        next_cursor:
          description: 'Token to get the next page of results. If `null`, there are no more pages.

            '
          minLength: 1
          nullable: true
          type: string
      required:
      - next_cursor
      type: object
    WatchlistFull_allOf_data_sanctions_sources:
      properties:
        name:
          description: Name of the source
          example: CIA World Factbook heads of state and government
          nullable: true
          type: string
        url:
          description: URL of the source
          example: https://www.opensanctions.org/datasets/us_cia_world_factbook
          nullable: true
          type: string
      required:
      - name
      - url
      type: object
    get_verifications_watchlists_200_response:
      properties:
        meta:
          $ref: '#/components/schemas/Pagination'
        data:
          items:
            $ref: '#/components/schemas/WatchlistMeta'
          type: array
      type: object
  securitySchemes:
    bearerAuth:
      scheme: bearer
      type: http
